### ISSUE TITLE
openshift.selector(selectorName).exists() throw Exception when doesn't exist

### ISSUE THREAD

**Issue by mbecca** [openshift/jenkins-client-plugin#263] opened 2019-05-03 15:50 UTC
Hello,

I have an error when execute 'openshift.selector(selectorName).exists()' to verify if a project exists

The error is:

ERROR: Unable to retrieve object names: selector([name=null],[labels=null],[namelist=[project/prueba-create-project]],[projectlist=null]); action failed: {reference={}, err=Error from server (Forbidden): projects.project.openshift.io "prueba-create-project" is forbidden: User "mbecca" cannot get projects.project.openshift.io in the namespace "prueba-create-project": no RBAC policy matched
, verb=get, cmd=oc --server=https://okd.server.ar:8443/ --insecure-skip-tls-verify --namespace=pruebas-s2i-jenkins --token=XXXXX get project/prueba-create-project -o=name --ignore-not-found , out=, status=1}

The project 'prueba-create-project' really doesn't exists ,  in this case this command will be return "false" instead of an exception?

If a project exists, this command return correctly.

Regards,

M.

**Comment by TomSchmitz** [comment] 2019-05-03 16:15
Ich bin bis 06.05.2019 abwesend.
I am out of the office until 06.05.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[openshift/jenkins-client-plugin] openshift.selector(selectorName).exists
() throw Exception when doesn't exist (#263)" gesendet am 03.05.2019
17:51:10.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by waveywaves** [comment] 2019-05-06 16:59
@mbecca Thanks for opening up this issue.

It does make more sense to throw an exception, like "ObjectNotFoundException" which is more appropriate in the case that this error comes up.

@gabemontero @sthaha What do you think ?

**Comment by saikirandusari** [comment] 2019-05-06 20:14
Error message clearly says. “Access forbidden”. Seems you do not have access to namespace selector object.We’ve had same issues and have resolved by performing below action.

Instead you could try 
def projectName=openshift.raw(“project -q”) 
and then perform null check on projectName.

Hope this helps.

**Comment by gabemontero** [comment] 2019-05-07 18:49
The analysis from @saikirandusari is correct.  And his workaround would just access the name of the current project.

And given that @waveywaves , we should not assume foribidden access == not found exception.

Cross namespace access of any is an escalated permission scenario in openshift, even if you want to simply check on its existence.

And if you wanted to provide project existence checks to your pipelines, you need to provide a openshift secret with escalated permissions, and map it to a jenkins credential.  Then use that credential from your pipeline.  Or you give escalated permissions to your users.

See https://github.com/openshift/jenkins-client-plugin#setting-up-credentials for mapping in and using a new credential.

**Closed by gabemontero** 2019-05-07 18:49 UTC

**Comment by mbecca** [comment] 2019-05-07 19:49
Hello,

I have all permission!, try execute this command with a non existing project.
In fact, if a project exists, this command (openshift.selector(selectorName).exists()) work perfectly!

Regards.

M

**Comment by gabemontero** [comment] 2019-05-07 20:07
ahh ...yeah I remember now that `oc` can be a little misleading sometimes wrt not founds and types like this @mbecca .... sorry for the confusion.

This can be easily proven by running 
`oc --server=https://okd.server.ar:8443/ --insecure-skip-tls-verify --namespace=pruebas-s2i-jenkins --token=XXXXX get project/prueba-create-project -o=name --ignore-not-found`

Where you specify your actual token with --token, in the jenkins master/agent pod you are running the pipeline in.

Unfortunately, this is an `oc` issue, and not something we can address with this plugin, as I mentioned before that we cannot assume that forbidden means not found, and would necessitate you opening an issue against openshift/origin, citing the `oc --server=https://okd.server.ar:8443/ --insecure-skip-tls-verify --namespace=pruebas-s2i-jenkins --token=XXXXX get project/prueba-create-project -o=name --ignore-not-found`
 example.

**Comment by gabemontero** [comment] 2019-05-07 20:19
Also, since our log does not print out the token, can you at least confirm you have an `openshift.withCrednetials(...)` line that points to a jenkins credential that has the token for `mbecca` that translate to the token you supply to `oc --server=https://okd.server.ar:8443/ --insecure-skip-tls-verify --namespace=pruebas-s2i-jenkins --token=XXXXX get project/prueba-create-project -o=name --ignore-not-found` when trying that from the pod commandl line.

**Comment by mbecca** [comment] 2019-05-07 22:50
Yeah, I have openshift.withCredentials(...) in jenkinsfile.
I have only cluster role binding for create or delete project in this another cluster. (we hace 2 cluster, non production and production clusters).

I repeat, if I try with a project that exists, the command works correctly. I suspect that when the project does not exist, I should not have permission to ask if the project exists in the cluster

My english is very poor :(

**Comment by gabemontero** [comment] 2019-05-07 23:51
On Tue, May 7, 2019 at 6:50 PM mbecca <notifications@github.com> wrote:

> Yeah, I have openshift.withCredentials(...) in jenkinsfile.
> I have only cluster role binding for create or delete project in this
> another cluster. (we hace 2 cluster, non production and production
> clusters).
>
Good catch.  Being able to create and delete a project requires different
permissions from being able to get or list projects.

Run these commands from the command line while logged into the clusters in
question:
- oc policy who-can create projects
- oc policy who-can delete projects
- oc policy who-can get projects
- oc policy who-can list projects

I bet your ID is not listed under either get or list

Also, I just ran a quick experiment in a local cluster installed via `oc
cluster up`

When logged in as "developer", running `oc get project foo` (where foo does
not exist) gets me:

Error from server (Forbidden): projects.project.openshift.io "foo" is
forbidden: User "developer" cannot get projects.project.openshift.io in the
namespace "foo": no RBAC policy matched

Look familiar, right ;-)

But if the foo project exists, I developer has roles in it, it works.

When I log in as the cluster admin, i.e. oc login -u system:admin

oc get project foo when foo does not exists results in

Error from server (NotFound): namespaces "foo" not found

So that is it.  While you cat create/delete/get your projects,
listing/getting any project is different.

**Comment by bo0ts** [comment] 2021-09-08 07:50
@gabemontero I recently ran into this issue again on OKD 4.7.

```
openshift.withCluster('dev2') {
    openshift.withProject('default') {
        def testProject = openshift.selector('project/test-project')
        if (deviceCenterProject.exists()) {
            testProject.delete()
        }
    }
}    
```

results in:

```
ERROR: Unable to retrieve object names: selector([name=null],[labels=null],[namelist=[projects/test-project]],[projectlist=null]); action failed: {err=, verb=get, cmd=oc --server=https://XXXXX:6443 --certificate-authority=XXXXX --namespace=default --token=XXXXX get projects/test-project -o=name , out=Error from server (NotFound): namespaces "test-project" not found
```

I've confirmed that the service account has all permissions on the project resource.

```
> oc policy who-can list projects | grep jenkins 
        system:serviceaccount:default:test-jenkins
> oc policy who-can get projects | grep jenkins
        system:serviceaccount:default:test-jenkins
> oc policy who-can create projects | grep jenkins
        system:serviceaccount:default:test-jenkins
> oc policy who-can delete projects | grep jenkins
        system:serviceaccount:default:test-jenkins
```

I've also confirmed that the pipeline uses the correct serviceaccount.

```
{
    "operation": "raw",
    "actions": [
        {
            "err": "",
            "verb": "",
            "cmd": "oc --server=https://XXXXX:6443 --certificate-authority=XXXXX --namespace=default --token=XXXXX  whoami ",
            "out": "system:serviceaccount:default:test-jenkins\n",
            "status": 0
        }
    ],
    "status": 0
}
```

**Comment by gabemontero** [comment] 2021-09-08 18:00
> @gabemontero I recently ran into this issue again on OKD 4.7.
> 
> ```
> openshift.withCluster('dev2') {
>     openshift.withProject('default') {
>         def testProject = openshift.selector('project/test-project')
>         if (deviceCenterProject.exists()) {
>             testProject.delete()
>         }
>     }
> }    
> ```
> 
> results in:
> 
> ```
> ERROR: Unable to retrieve object names: selector([name=null],[labels=null],[namelist=[projects/test-project]],[projectlist=null]); action failed: {err=, verb=get, cmd=oc --server=https://XXXXX:6443 --certificate-authority=XXXXX --namespace=default --token=XXXXX get projects/test-project -o=name , out=Error from server (NotFound): namespaces "test-project" not found
> ```
> 
> I've confirmed that the service account has all permissions on the project resource.
> 
> ```
> > oc policy who-can list projects | grep jenkins 
>         system:serviceaccount:default:test-jenkins
> > oc policy who-can get projects | grep jenkins
>         system:serviceaccount:default:test-jenkins
> > oc policy who-can create projects | grep jenkins
>         system:serviceaccount:default:test-jenkins
> > oc policy who-can delete projects | grep jenkins
>         system:serviceaccount:default:test-jenkins
> ```
> 
> I've also confirmed that the pipeline uses the correct serviceaccount.
> 
> ```
> {
>     "operation": "raw",
>     "actions": [
>         {
>             "err": "",
>             "verb": "",
>             "cmd": "oc --server=https://XXXXX:6443 --certificate-authority=XXXXX --namespace=default --token=XXXXX  whoami ",
>             "out": "system:serviceaccount:default:test-jenkins\n",
>             "status": 0
>         }
>     ],
>     "status": 0
> }
> ```

Just tried it and it works for me @bo0ts 

A couple of notes:
- ignoring of not found errors is a function of the underlying `oc` implementation that is made available to the plugin through jenkins global tool configuration
- in particular, we look for support of the `--ingore-not-found` flag ... see  https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L74-L78  and https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L1520-L1530
- per those links, you could run with `FINE` level tracing for com.openshift.jenkins.plugins.* and see what shows up for those trace statements
