### ISSUE TITLE
Selector does not work with multiple labels

### ISSUE THREAD

**Issue by tanskann** [openshift/jenkins-client-plugin#30] opened 2017-06-07 12:04 UTC
When I have 2 BuildConfigs in Openshift like this:

BuildConfig 1 labels:

    ref: master
    app: my-app

BuildConfig 2 labels:

    ref: master
    app: my-second-app

I expect 
```
def buildConfigSelector = openshift.selector('bc', [ref: 'master', app: 'my-third-app'])
if (buildConfigSelector.count() > 0) {
 sh 'more than 0'
}
else {
 sh 'no more than 0'
}
```

to print `no more than 0`. But currently it selects either BuildConfig 1 or BuildConfig 2. I can verify this using

```
def result = buildConfigSelector.describe()
sh "echo $result"
```

Describe prints BuildConfig 1 or BuildConfig 2.

**Comment by bparees** [comment] 2017-06-07 13:52
what oc version is your jenkins server using?

the multiple -l syntax works as expected for me:
```
$ oc get pods -l app=ruby-helloworld-sample -l deployment=database-1
NAME               READY     STATUS    RESTARTS   AGE
database-1-f0kds   1/1       Running   0          1m
```

```
$ oc get pods -l app=ruby-helloworld-sample -l deployment=database-2
No resources found.
```

**Comment by tanskann** [comment] 2017-06-07 14:10
Tried with 1.4.1 and 1.5.1 with same results
```
$ oc version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server <Redacted>
openshift v3.5.5.15
kubernetes v1.5.2+43a9be4

$ oc get bc -l ref=dsl -l app=helloworld-advanced
NAME                            TYPE      FROM            LATEST
helloworld-advanced-dsl         Source    Git@dsl         26
helloworld-advanced-dsl-new-2   Source    Git@dsl-new-2   7
$ oc describe bc helloworld-advanced-dsl
Name:       helloworld-advanced-dsl
Namespace:  test
Created:    3 weeks ago
Labels:     app=helloworld-advanced
            ref=dsl
Annotations:    <none>
Latest Version: 26

Strategy:       Source
URL:            <Redacted>
Ref:            dsl
Source Secret:      git
From Image:     ImageStreamTag openshift/nodejs:latest
Output to:      DockerImage <Redacted>
Post Commit Hook:   ["/bin/sh", "-ic", "npm test"]
Push Secret:        <Redacted>

Build Run Policy:   Serial
Triggered by:       <none>

Build               Status      Duration    Creation Time
<Redacted>

No events.

$ oc describe bc helloworld-advanced-dsl-new-2
Name:       helloworld-advanced-dsl-new-2
Namespace:  test
Created:    9 days ago
Labels:     app=helloworld-advanced
            ref=dsl-new-2
Annotations:    <none>
Latest Version: 7

Strategy:       Source
URL:            <Redacted>
Ref:            dsl-new-2
Source Secret:      git
From Image:     ImageStreamTag openshift/nodejs:latest
Output to:      DockerImage <Redacted>
Post Commit Hook:   ["/bin/sh", "-ic", "npm test"]
Push Secret:        <Redacted>

Build Run Policy:   Serial
Triggered by:       <none>

Build                   Status      Duration        Creation Time
<Redacted>

No events.

$ oc get bc -l ref=dsl,app=helloworld-advanced
NAME                      TYPE      FROM      LATEST
helloworld-advanced-dsl   Source    Git@dsl   26
```

**Comment by bparees** [comment] 2017-06-07 15:46
it appears that label selection is matching anything with the prefix of the label you specified when you specify multiple labels. 

as seen here, if you specify a single partial label, no matches are found:
```
$ oc get pods -l app=ruby-helloworld
No resources found.
```

and if you specify that label plus another, then you get matches:
```
$ oc get pods -l app=ruby-helloworld -l deployment=database-1
NAME               READY     STATUS    RESTARTS   AGE
database-1-7xfbk   1/1       Running   0          2m
```

the pod in question has the following labels:
```
Labels:	        app=ruby-helloworld-sample
			deployment=database-1
			deploymentconfig=database
			name=database
```

 this is a bug in openshift/k8s and should be opened/reported there.  @liggitt 

i'm going to close this because changing the jenkins client plugin to use the comma syntax would be a regression in behavior.  using multiple -l flags is the right thing to do, the underlying oc get behavior needs to be fixed.

**Comment by bparees** [comment] 2017-06-07 15:46
just to finish the permutations of my example:
```
$ oc get pods -l app=ruby-helloworld,deployment=database-1
No resources found.
```

**Comment by bparees** [comment] 2017-06-07 15:48
hm.  further tests make me think the multple -l syntax effectively ORs the labels together.  that's surprising behavior to me since it doesn't match how the comma syntax works.  @fabianofranz  @liggitt is that the intended behavior?

**Comment by bparees** [comment] 2017-06-07 16:09
(I still don't think we're going to want to change what the plugin does here, but if there's a doc update needed to make it clear you get OR behavior when you specify multiple labels, we can do that.)

**Comment by tanskann** [comment] 2017-06-08 06:46
IMO OR behavior does not make that much sense - AND operator should be implemented if the intended behaviour of this selector is OR, but I agree this seems to be problem with oc itself rather than with this plugin. Closing related PR #31

**Comment by bparees** [comment] 2017-06-08 14:28
actually on yet another investigation of this, it appears "oc get pods -l label1 -l label2" simply respects the second label and ignores the first.

which also feels like a bug in oc to me.

**Comment by bparees** [comment] 2017-06-08 15:03
i've opened an issue here to discuss the behavior:
https://github.com/openshift/origin/issues/14525

depending on the outcome of that issue, we may want to accept your PR after all.

**Closed** 2017-06-28 17:38 UTC
