### ISSUE TITLE
openshift.process(...) or apply(...) results in the path "/tmp/.....markup" does not exist

### ISSUE THREAD

**Issue by toschder** [openshift/jenkins-client-plugin#245] opened 2019-03-11 20:34 UTC
[BuildConfig.zip](https://github.com/openshift/jenkins-client-plugin/files/2958809/BuildConfig.zip)

Hi, 
I tried to implement the CLI commands
`oc process -n $project -f BuildConfig.yml | oc apply -n $project -f -`

with the following code:

```
		def buildConfigYaml = script.readYaml file: 'BuildConfig.yml'
		
		openshift.logLevel(3)
		openshift.withCluster(clusterName) {
			openshift.withProject(project) {
// TODO gives strange exception:
//				failed to read input object (not a Template?): the path "/tmp/process5179732242846817041.markup" does not exist
				 
				def created = openshift.process(buildConfigYaml)
				def selector = openshift.apply(created)
				selector.logs("-f")
				
				// oc start-build
				selector = openshift.startBuild(buildConfigName,"--from-dir=.", "--wait")
				selector.logs("-f")
			}
		}

```
I´m wondering why the readYaml file will be written to a temporary .markup file - and that file isn´t found afterwards.
The error I receive is:
`failed to read input object (not a Template?): the path "/tmp/process5179732242846817041.markup" does not exist`

Expected behaviour is that passing a Map to openshift.process(.....) will work without that error message.
Any ideas what´s going wrong here?

I´m using openShift 3.6, the latest plugin version.
When running the above code on an openShift Jenkins-Slave the error occurs - the same code executed on for example an openStack Slave is working ?

**Comment by gabemontero** [comment] 2019-03-12 20:28
can you provide the actual yaml that is in `buildConfigYaml` @toschder 
both when it fails, and when it succeeds

**Comment by toschder** [comment] 2019-03-12 21:16
I´ve added it to my first post (BuildConfig.zip) - the problem is not the BuildConfig.yml itself - it looks like it has something todo with the jenkins slave. On "simple" Unix-Slaves it´s working - on Slaves started with the Kubernetes plugin in openShift it´s not working. Any suggestion how to "debug" this? The createTempTextFile(...) seems to work (there´s no PermissionDenied or whatever exception)

**Comment by vfreex** [comment] 2019-03-13 04:22
Are you running your agent in the default jnlp container or a sidecar container? Kubernetes plugin uses different ways of launching process.

**Comment by fyuan1316** [comment] 2019-03-13 11:06
+1
Encountered the same problem， use:
1)  kubernetes plugin
2) pod has 3 containers  and  openshift.withProject{} in a sidecar

...
copyobj = openshift.selector(kind, instance_name).object()
copyobj.status.state = 'init'
openshift.apply(copyobj)
...

```
ERROR: apply returned an error;
{reference={/tmp/apply8572908460067911222.markup={"metadata":{"generation":17,"uid":"ab05b27c-426c-11e9-8e97-5254006e2ac3","resourceVersion":"1630401","creationTimestamp":"2019-03-09T13:10:10Z","name":"notebook-sample","namespace":"default","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"xx.xxxx.io/v1alpha1\",\"kind\":\"NoteBook\",\"metadata\":{\"annotations\":{},\"labels\":{\"controller-tools.k8s.io\":\"1.0\"},\"name\":\"notebook-sample\",\"namespace\":\"default\"},\"spec\":{\"framework\":{\"image\":\"index.xxxx.cn/xxxx/tensorflow-1.8.0-notebook-cpu:v0.5.7\",\"type\":\"tensorflow\",\"version\":\"1.6\"},\"pvc\":[],\"quota\":{\"hard\":{\"limits.cpu\":\"2\",\"limits.memory\":\"2Gi\",\"pods\":\"4\",\"requests.cpu\":\"0.4\",\"requests.memory\":\"50Mi\"}},\"user\":\"ff\"}}\n"},"labels":{"controller-tools.k8s.io":"1.0"},"selfLink":"/apis/ml.xxxxx.io/v1alpha1/namespaces/default/notebooks/notebook-sample"},"apiVersion":"ml.xxxx.io/v1alpha1","kind":"NoteBook","spec":{"framework":{"image":"index.xxxx.cn/xxxxxxx/tensorflow-1.8.0-notebook-cpu:v0.5.7","type":"tensorflow","version":"1.6"},"pvc":[],"user":"ff","quota":{"hard":{"limits.cpu":"2","limits.memory":"2Gi","pods":"4","requests.memory":"50Mi","requests.cpu":"0.4"}}},"status":{"state":"init"}}}, err=, verb=apply, cmd=oc --server=https://10.96.0.1:443 --insecure-skip-tls-verify --namespace=default --token=XXXXX apply -f /tmp/apply8572908460067911222.markup -o=name , out=error: the path "/tmp/apply8572908460067911222.markup" does not exist, status=1}
```

**Comment by vfreex** [comment] 2019-03-13 11:27
I think I figured out why this issue happens:

You are calling those functions from a sidecar container of a Kubernetes plugin created pod.

1. When applying an object to `openshift.apply()` or `openshift.process()`, a temporary file is created in the `jnlp` container.

2. But when actually running `openshift.apply()` or `openshift.process()`, `oc` tries to access the temporary file from the sidecar container. It accesses the filesystem from a wrong container!

The solution could be one of the following options:

1. Share the `/tmp` directories between all containers of the agent pod by mounting to a `EmptyDir` volume.
2. Make this plugin handle this situation.

**Comment by vfreex** [comment] 2019-03-13 11:31
For option 2, I think we can directly pump the json content into stdin of `oc` process if #243 is merged.

**Comment by toschder** [comment] 2019-03-13 11:34
sounds like a good strategy - what I don´t understand: What´s the need to write a temporary file? Could´nt this be removed completely?

**Comment by vfreex** [comment] 2019-03-13 12:04
@toschder It is how the plugin implements the `apply()` and `process()` functions for an object: It serializes the object to a temporary JSON file first, then calls `oc apply|process -f <path-to-the-temporary-file>` to finish the action.

**Comment by vfreex** [comment] 2019-03-16 12:11
Unfortunately, when using k8s plugin's container agent, redirecting stdin is not supported.
That plugin has more limitations than we imagine.

**Comment by toschder** [comment] 2019-03-16 12:39
Hi all, would it be an option to use workspace@tmp directory instead of java.io.tempdir ? From my point of view this would make more sense (files belong to whats going on in the workspace) - and the workspace dir is shared between side-car and main container. This would solve the issue by only a small change.

**Comment by vfreex** [comment] 2019-03-17 06:33
@toschder  Yeah, this sounds like a good plan.

**Comment by gabemontero** [comment] 2019-03-18 19:31
Thanks for the analysis @toschder @vfreex 

I've created PR https://github.com/openshift/jenkins-client-plugin/pull/248 to facilitate the suggestion and start regression testing

As an FYI, the non-use of a workspace tmp dir dates back to the original creation of this plugin (prior to my direct involvement) back when we first discovered the old docker workflow plugin and its docker global variable.

No telling what Jenkins bugs / behaviors at that time might have driven the decision (I talked with the original author but we cannot remember anything off hand from that time 2 plus years ago).

At this point, if things pass the regression suite, I could see adding this sometime this week.

@toschder - any chance you could try a pre-release plugin file?

Here is a zip of the locally built hpi file with the change
[client-plugin-1.zip](https://github.com/openshift/jenkins-client-plugin/files/2979923/client-plugin-1.zip)

**Comment by vfreex** [comment] 2019-03-19 11:09
@gabemontero Thanks. I don't have time to test this recently but it seems to be good. 👍

**Closed** 2019-03-19 17:57 UTC

**Comment by gabemontero** [comment] 2019-03-19 18:01
initiated v1.0.29 of the plugin to pick up the fix for this

**Comment by fyuan1316** [comment] 2019-03-21 06:55
hi，all:
I solved this problem in another way, maybe it is also suitable for you. :smile: 
In the "kuberntes pod template" parameter configuration item, I added the data volume type of the pod to emptydir and the path to "/tmp".
![image](https://user-images.githubusercontent.com/42265657/54736921-69246700-4be8-11e9-8870-4f6a6b42d046.png)
