### ISSUE TITLE
java.nio.file.NoSuchFileException after upgrade to 1.0.6

### ISSUE THREAD

**Issue by schuch** [openshift/jenkins-client-plugin#121] opened 2018-02-14 14:45 UTC
We updated the jenkins-client-plugin to 1.0.6 today and encountered the following error when executing openshift commands to the cluster from a jenkins pipeline:

```
java.nio.file.NoSuchFileException: /var/run/secrets/kubernetes.io/serviceaccount/token
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at hudson.FilePath$33.invoke(FilePath.java:1782)
	at hudson.FilePath$33.invoke(FilePath.java:1777)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2760)
	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:358)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Caused: java.io.IOException
	at hudson.remoting.FastPipedInputStream.read(FastPipedInputStream.java:169)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2001)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1980)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1957)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1907)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:778)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:803)
	at org.jenkinsci.plugins.workflow.steps.ReadFileStep$Execution.run(ReadFileStep.java:97)
	at org.jenkinsci.plugins.workflow.steps.ReadFileStep$Execution.run(ReadFileStep.java:86)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Our Setup is:
External Jenkins 2.89.2 (not running in openshift)

OC Binary:

```
ubuntu@ip-xx-xx-xx-xx:~$ oc version
oc v3.6.173.0.5
kubernetes v1.6.1+5115d708d7
Server https://*************:443
openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
```

Snippet from the Jenkinsfile:
```
openshift.withCluster('test-cluster') {
        openshift.withProject('example-namespace') {
                def entities = openshift.process('-f', "template.yaml")
        }
}
```
"test-cluster" is properly configured in the globald jenkins configuration.

According to the docs the file `/var/run/secrets/kubernetes.io/serviceaccount/token` would be looked up when using the "default" cluster, e.g. when withCluster() is called without argument, which should not be the case in our example.

When switching back to 1.0.5, the error disappears.

**Comment by gabemontero** [comment] 2018-02-14 14:50
I suspect this will be addressed by https://github.com/openshift/jenkins-client-plugin/pull/120

But I'll do some causal analysis via cross referencing with the v1.0.5 version to confirm this, as well as understand how this was introduced.

**Comment by gabemontero** [comment] 2018-02-14 15:01
Yeah it was introduced with 3cc103d36bc31dbb09f010c3b43aaae8df6fbfb2, the first post v1.0.5 commit

Since we can't cover none default clusters in out automated tests, we missed this one.

@bparees @coreydaley fyi

**Comment by gabemontero** [comment] 2018-02-14 15:02
And confirmed https://github.com/openshift/jenkins-client-plugin/pull/120 should address

Starting plugin update / image update process.

**Comment by gabemontero** [comment] 2018-02-14 15:12
v1.0.7 is cooking now in jenkinsci .... look for the new version at the update center

**Closed** 2018-02-14 15:12 UTC

**Comment by schuch** [comment] 2018-02-15 07:19
successfully tested with 1.0.7
many thanks for this F1 :racing_car:  speed response / bugfix

**Comment by schuch** [comment] 2018-02-15 07:20
successfully tested with 1.0.7
many thanks for this F1 :racing_car:  speed response / bugfix

**Comment by gabemontero** [comment] 2018-02-15 12:35
Thanks for the confirmation - glad to help.
