### ISSUE TITLE
version 1.0.8 untilEach: watch closure threw an exception: "java.lang.IndexOutOfBoundsException: Index: 1, Size: 1; Index: 1, Size: 1".

### ISSUE THREAD

**Issue by TomSchmitz** [openshift/jenkins-client-plugin#130] opened 2018-03-19 09:33 UTC
with version 1.0.8 the untilEach function throws an IndexOutOfBoundsException.

we use the untilEach function to wait for pods to be running after a rollout of a deploymentConfig.
during the iteration the jenkins console output shows the following error:
watch closure threw an exception: "java.lang.IndexOutOfBoundsException: Index: 1, Size: 1; Index: 1, Size: 1".
the untilEach iteration will not get the true-condition to terminate the watch on the pods to be running.

here is a code example, which runs into the error described above:
```
def dcRelatedPods = deploymentConfig.related('pods')
def podObj
dcRelatedPods.untilEach(1) {
  podObj = it.object()
  return podObj.status.phase == 'Running'
} 
```

With the version 1.0.2-1.0.7 the code runs perfectly.
Is it a new behaviour or is it a bug?

Please provide help.

Thank you 
Tom

**Comment by gabemontero** [comment] 2018-03-20 17:24
hey @TomSchmitz - sound like a bug has been introduced

I have not been able to reproduce locally, constructing test cases like your sample.

Could you possibly provide the entire stack trace of the IndexOutOfBoundsException you received?

**Comment by TomSchmitz** [comment] 2018-03-21 09:10
hello @gabemontero,

in the attached file you can see the stacktrace. classes with package starting with de.generali.jenkins are our classes which wrapps the functionality of the openshift jenkins client plugin.
[indexOutOfBoundsExceptionStatcktrace.txt](https://github.com/openshift/jenkins-client-plugin/files/1832554/indexOutOfBoundsExceptionStatcktrace.txt)

If you need more information, let me know.

Thank you.
Best regards Tom

**Comment by gabemontero** [comment] 2018-03-21 20:18
Thanks @TomSchmitz - the stack trace was very helpful, as was revealing the fact you all have extended our groovy shim (first I have heard of that ... very clever ... but not something I would say we would agree to support in a first class manner).

As it turns out, v1.0.8 introduced changes we needed to support api objects in a list spread across multiple namespaces/projects ... a usage pattern that was becoming more and more prevalent.

The multi-project work very well may have had impacts on your wrappers of the OpenShiftDSL.groovy and broken assumptions you have made  ... for example, I see you've wrappered withProject ... by name alone that could be something.

Even with my statements on officially supporting the scenario as a backdrop, we can still see if it is something we can easily resolve ... or at least provide guidance on how you need to adjust your wrapper.

Is there any chance you can share the code for either
a) `generali-openshift-jenkins-library/src/de/generali/jenkins/OpenShiftProject.groovy` in general
b) or at least enough of `de.generali.jenkins.OpenShiftProject.withProject` and `de.generali.jenkins.OpenShiftProject.watchRolloutStatus` and any other OpenShiftDSL.groovy wrapped methods they might call?

@bparees check it out / fyi ^^

**Comment by TomSchmitz** [comment] 2018-03-22 11:47
hello @gabemontero, 
i need some time to get permission to share the code.
Hopefully i can return to you tomorrow...

**Comment by TomSchmitz** [comment] 2018-03-23 09:03
hello @gabemontero, as requested here is the full class OpenShiftProject.groovy in the zip-file, which wrapps the functionality: 
[OpenShiftProject.zip](https://github.com/openshift/jenkins-client-plugin/files/1840809/OpenShiftProject.zip)

Thank you for your help.
Tom

**Comment by gabemontero** [comment] 2018-03-26 20:10
ok @TomSchmitz , the src code was very helpful and confirmed/expedited things

After seeing what your wrapper does, since it does not extend our OpenShiftDSL class per se, it is not quite as frightening as I thought :-) ... definitely just a proxy/adapter pattern, depending on your favorite choice of words there

That said, in the future, I'll most likely need the src each time, to see exactly what use of `openshift` exists in each of the wrapper's methods.... similar to getting typically getting the raw pipeline snippets from folks who call us directly from their Jenkinsfile.

And from that src code, I'm pretty sure that you need the fix from commit 64e26203153023c271377852fa99b272b27e7a86 which I recently did.  The rollout stuff calls withEach, where this fix was needed.

I hope to be cutting a new version of the plugin with that change sometime this week, but have a few higher priority things I need to get to first.

If you can wait, great.  If not, would it be possible for you to build your own version of the plugin from the latest at https://github.com/openshift/jenkins-client-plugin and see if it fixes your situation?

If not, and subsequent stack trace would be helpful in uncovering any additional fixes needed.

thanks

**Comment by TomSchmitz** [comment] 2018-03-27 08:37
hello @gabemontero,
no problem to share code with you, i have permission for future issues right now.
Sorry for my incorrectness, of course it is a adapter-pattern that we are using.

We can wait for the fix, we are running with version 1.0.7 perfectly at the moment.

Thanks
Tom

**Comment by TomSchmitz** [comment] 2018-03-28 07:05
@gabemontero  i have one more question. if you want me to create a new issue for that, let me know.
Here is the question: Is there a changelog of the plugin, so users can inform themselves what changes and new features are added to new versions of the plugin?

**Comment by gabemontero** [comment] 2018-03-28 12:02
Hey @TomSchmitz 

There is not a changelog currently but there is already an issue opened for that.

Does the watch/unwatch button show for you at the top of the repo when you bring it up in a browser?

**Comment by TomSchmitz** [comment] 2018-03-28 12:16
hi @gabemontero , i am already watching the repo since i have opened this issue

**Comment by TomSchmitz** [comment] 2018-04-04 13:34
Hey @gabemontero,

after recognizing that plugin version 1.0.9 was released, we have updated our test jenkins with the new version.

We still have an issue. This time it is another error but still localized inside the untilEach iteration in the context described in my first post.
Here is the new error: 
**watch closure threw an exception: "hudson.AbortException: projects were not set for selector([name=pods],[labels={deploymentconfig=grape-spring-boot-container-verification}],[namelist=null],[projectlist=[grape-regtest-tools-aete]]); projects were not set for selector([name=pods],[labels={deploymentconfig=grape-spring-boot-container-verification}],[namelist=null],[projectlist=[grape-regtest-tools-aete]])".**

I also want to provide the stacktrace in the following file: 
[stacktrace109untilEach.txt](https://github.com/openshift/jenkins-client-plugin/files/1875916/stacktrace109untilEach.txt)

Please let me know, if you need more info on this.

Because this is not related to version 1.0.8 and the problem occured in version 1.0.9 with another error message, we can close this issue and reopen a new one. Just inform me...

Thank you.
Regards 
Tom

**Comment by gabemontero** [comment] 2018-04-04 18:47
Hey @TomSchmitz no we can continue to use this change.  It appears some of the subsequent fixes prior to cutting the release broke the fix here.  The test case I originally constructed to validate the fix for this was not enabled yet, and it is failing for me now.

**Comment by gabemontero** [comment] 2018-04-04 18:47
Debugging as I type

**Comment by gabemontero** [comment] 2018-04-04 19:12
Well I take that back, sort of ... it failed for me the very first time:

```
Started by user developer
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/jobs/asdf/workspace
[Pipeline] {

[Pipeline] echo
[Pipeline] _OcContextInit
[Pipeline] _OcContextInit
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: projects were not set for selector([name=pod],[labels={app=asdf}],[namelist=null],[projectlist=null])
Finished: FAILURE
```

But has passed on all subsequent runs:

```
Started by user developer
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/jobs/asdf/workspace
[Pipeline] {
[Pipeline] echo

[Pipeline] _OcContextInit
[Pipeline] _OcContextInit
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

Any chance @TomSchmitz you are seeing similar results ?

Whatever this oddity is, I'm sure it is groovy related :-(

**Comment by gabemontero** [comment] 2018-04-04 20:38
Yeah I've since restarted openshift, redeployed the pod, and am still seeing no further instances of the abort exception.  Still very curious @TomSchmitz if repeated runs with v1.0.9 shows anything similar.

I might need you to run with a debug jar I would provide if you are seeing it consistently.

**Comment by TomSchmitz** [comment] 2018-04-05 14:13
hey @gabemontero, 
i see that consistently. But i found a workaround that only works once sadly. So no option for us to go with 1.0.9.
If you delete all deploymentconfigs of the application in the namespace via  
**`oc delete dc <<app-name>> -n <<namespace/poject>>`** the pipeline job will pass successfully without any instances of the abort exception. 
But one more curious thing: in openshift you can see that a dc is created with nr 1, but this dc will be cancelled with the status reason **"newer deployment was found running"**. another dc with nr 2 is created which rollout successfully. 

As I said, the workaround works once, any further rollout of replaced new dc's based on a template (also deployed to openshift by the plugin) will be running in an instance of the abort exception with the described error. 

One additional information: the deployment on openshift side is successfull, we just have the problem on jenkins/plugin side that the untilEach iteration does not terminate.

May this is required for you to understand whats going on, i attach the jenkins output file when a pipeline job will not be terminated caused by the until each iteration. this is the output when `watchRolloutStatus` is called: 
[watchRolloutStatusOutput.txt](https://github.com/openshift/jenkins-client-plugin/files/1880338/watchRolloutStatusOutput.txt)

If you need more info, let me know.

Thank you 
Tom

**Comment by gabemontero** [comment] 2018-04-05 18:16
Hey @TomSchmitz 

Ok, the deployment aspect of this changed my viewpoint on this and I now may understand what is going on.  There is a timing element involved here, as the `withEach` clause is ultimately performing an `oc get` and based on the results it gets, we may hit this.  In my testing, I was just dealing with pods in my prior testing.   The change to address, while certainly doable, is not trivial.

Would it be possible for you to take a pre-release version of the plugin and validate against your cluster?  Getting some early results from your env could expedite the overall resolution, as replicating the timing on my end could be problematic.

**Comment by TomSchmitz** [comment] 2018-04-05 22:41
Sry for not being clear enough from the beginning ;)

**Comment by gabemontero** [comment] 2018-04-06 15:46
Great - thanks @TomSchmitz  !

I'm attaching a zipped hpi file here 
[openshift-client.zip](https://github.com/openshift/jenkins-client-plugin/files/1884652/openshift-client.zip)


Note - I've added some debug statement starting with "GGM" that will show up in the job run console log.  If something is amiss I'll want to look at that along with the sample script (if it is not the same as the one above) and possibly the jenkins pod logs.

Thanks again

**Comment by donovanmuller** [comment] 2018-04-09 12:55
Having the same issue as mentioned at https://github.com/openshift/jenkins-client-plugin/issues/130#issuecomment-378601493 with `openshift-client:1.0.9`. 
I.e. `projects were not set for selector([name=pod],[labels={deployment=test-application-6}],[namelist=null],[projectlist=null])` with the following:

``` groovy
    stage('Deploy to DEV') {
      sh ': Deploying to DEV...'

      openshift.withProject(projectDevProject) {
        ...
        timeout(5) {
          openshift.selector('dc', app).rollout().latest()
          def deploymentObject = openshift.selector('dc', app).object()
          if (deploymentObject.spec.replicas > 0) {
            def podSelector = openshift.selector('pod', [deployment: "${app}-${deploymentObject.status.latestVersion}"])
            podSelector.untilEach {
              echo "Deployment [${deploymentObject.status.latestVersion}] with Pod [${it.object().metadata.name}] is ready?: ${it.object().status.containerStatuses[0].ready}"
              return it.object().status.containerStatuses[0].ready
            }
          } else {
              echo "Deployment has a replica count of 0. Not waiting for Pods to become healthy..."
          }
        }
      }
    }
```

See also #131.

Have used the pre-release version and it works:

```console
```

**Comment by gabemontero** [comment] 2018-04-09 14:05
Thanks for the confirmation @donovanmuller 

I've received similar confirmation from some of the other upstream users.

The PR merge / new version of the plugin / image update process will be starting shortly.

**Comment by TomSchmitz** [comment] 2018-04-09 15:32
hi @gabemontero, 

sorry for my late reply. I also can confirm that it is working now. 

Thank you! Tom

**Comment by gabemontero** [comment] 2018-04-09 15:34
no worries @TomSchmitz and thanks for confirming

**Closed** 2018-04-10 22:54 UTC
Labels: bug
